## Countries Data API Project

In [53]:
import requests
import pandas as pd
import numpy as np

Test the API with a random country and some of its data first:

In [64]:
test_url = "https://restcountries.com/v3.1/name/china"

response = requests.get(test_url)
if response.status_code == 200:
    country_data = response.json()

    # since the native names for the countries are in nested dicts of different languages, the below logic will standardize it
    native_names = country_data[0]["name"]["nativeName"]
    first_native_key = list(native_names.keys())[0]
    native_name = native_names[first_native_key]["official"]

    print(f"Name: {country_data[0]['name']['common']}")
    print(f"Native Name: {native_name}")
    print(f"Capital: {country_data[0]['capital'][0]}")
    print(f"Population: {country_data[0]['population']}")

else:    print(f"Error: {response.status_code}")

Name: China
Native Name: 中华人民共和国
Capital: Beijing
Population: 1408280000

In [55]:
all = "https://restcountries.com//v3.1/all?fields=name"
response = requests.get(all)
if response.status_code == 200:
    country_data = response.json()
    print(f"Name: {country_data[0]['name']['common']}")


else:    print(f"Error: {response.status_code}")

Error: 404

### Method:
1. Create empty DataFrame with specified columns
2. Create a function which will take in a country's name, and will get the specified info AND populate a row in the DataFrame
3. Clean the filled in DataFrame if needed
4. Convert the DataFrame to CSV or JSON???

In [65]:
# Create an empty DataFrame with specified columns and 10 rows for 10 countries
df = pd.DataFrame(columns=['Name', 'Native Name', 'Capital(s)', 'Population', 'Languages', 'Region'])
df

Empty DataFrame
Columns: [Name, Native Name, Capital(s), Population, Languages, Region]
Index: []

In [70]:
base_url = "https://restcountries.com/"

# Fill in the DataFrame with the given country's information
def get_country_info(name):
    url = f"{base_url}v3.1/name/{name}"
    response = requests.get(url)
 
    if response.status_code == 200:
        country_data = response.json() # if connection is successful, the data will be in json format and can be parsed as a dict

        # since the native names for the countries are in nested dicts of different languages, the below logic will standardize it
        native_names = country_data[0]["name"]["nativeName"]
        first_native_key = list(native_names.keys())[0]
        native_name = native_names[first_native_key]["official"]

        # Same format fix for languages as well
        languages = country_data[0]['languages']
        first_language_key = list(languages.keys())[0]
        language = languages[first_language_key]


        df.loc[len(df)] = [country_data[0]['name']['common'], native_name, country_data[0]['capital'][0], country_data[0]['population'], language, country_data[0]['region']]

    else:
        print(f"Failed to retrieve data for {name}. Status code: {response.status_code}")


# 10 countries to retrieve information for:

get_country_info("America")
get_country_info("Canada")
get_country_info("Pakistan")
get_country_info("India")
get_country_info("Korea")
get_country_info("China")
get_country_info("Japan")
get_country_info("Switzerland")
get_country_info("Italy")
get_country_info("Norway")


df

,Name,Native Name,Capital(s),Population,Languages,Region
0,United States,中华人民共和国,"[Washington, D.C.]",340110988,English,Americas
1,Canada,中华人民共和国,[Ottawa],41651653,English,Americas
2,Pakistan,中华人民共和国,[Islamabad],241499431,English,Asia
3,India,中华人民共和国,[New Delhi],1417492000,English,Asia
4,United States,中华人民共和国,"[Washington, D.C.]",340110988,English,Americas
5,Canada,中华人民共和国,[Ottawa],41651653,English,Americas
6,Pakistan,中华人民共和国,[Islamabad],241499431,English,Asia
7,India,中华人民共和国,[New Delhi],1417492000,English,Asia
8,United States,United States of America,"[Washington, D.C.]",340110988,English,Americas
9,Canada,Canada,[Ottawa],41651653,English,Americas
10,Pakistan,Islamic Republic of Pakistan,[Islamabad],241499431,English,Asia
11,India,Republic of India,[New Delhi],1417492000,English,Asia
12,United States,United States of America,"[Washington, D.C.]",340110988,English,Americas
13,Canada,Canada,[Ottawa],41651653,English,Americas
14,Pakistan,Islamic Republic of Pakistan,[Islamabad],241499431,English,Asia
15,India,Republic of India,[New Delhi],1417492000,English,Asia
16,North Korea,조선민주주의인민공화국,[Pyongyang],25950000,Korean,Asia
17,China,中华人民共和国,[Beijing],1408280000,Chinese,Asia
18,Japan,日本,[Tokyo],123210000,Japanese,Asia
19,Switzerland,Confédération suisse,[Bern],9082848,French,Europe
20,Italy,Repubblica italiana,[Rome],58927633,Italian,Europe
21,Norway,Kongeriket Noreg,[Oslo],5606944,Norwegian Nynorsk,Europe
22,United States,United States of America,"Washington, D.C.",340110988,English,Americas
23,Canada,Canada,Ottawa,41651653,English,Americas
24,Pakistan,Islamic Republic of Pakistan,Islamabad,241499431,English,Asia
25,India,Republic of India,New Delhi,1417492000,English,Asia
26,North Korea,조선민주주의인민공화국,Pyongyang,25950000,Korean,Asia
27,China,中华人民共和国,Beijing,1408280000,Chinese,Asia
28,Japan,日本,Tokyo,123210000,Japanese,Asia
29,Switzerland,Confédération suisse,Bern,9082848,French,Europe
30,Italy,Repubblica italiana,Rome,58927633,Italian,Europe
31,Norway,Kongeriket Noreg,Oslo,5606944,Norwegian Nynorsk,Europe

In [72]:
# During all the testing, many duplicate entries were added to the DataFrame. Let's remove the test ones at the beginning

df = df.drop(df.index[0:21])
df

,Name,Native Name,Capital(s),Population,Languages,Region
21,Norway,Kongeriket Noreg,[Oslo],5606944,Norwegian Nynorsk,Europe
22,United States,United States of America,"Washington, D.C.",340110988,English,Americas
23,Canada,Canada,Ottawa,41651653,English,Americas
24,Pakistan,Islamic Republic of Pakistan,Islamabad,241499431,English,Asia
25,India,Republic of India,New Delhi,1417492000,English,Asia
26,North Korea,조선민주주의인민공화국,Pyongyang,25950000,Korean,Asia
27,China,中华人民共和国,Beijing,1408280000,Chinese,Asia
28,Japan,日本,Tokyo,123210000,Japanese,Asia
29,Switzerland,Confédération suisse,Bern,9082848,French,Europe
30,Italy,Repubblica italiana,Rome,58927633,Italian,Europe
31,Norway,Kongeriket Noreg,Oslo,5606944,Norwegian Nynorsk,Europe

In [ ]:
df = df.iloc[1:] # need to drop one more oops
df

,Name,Native Name,Capital(s),Population,Languages,Region
22,United States,United States of America,"Washington, D.C.",340110988,English,Americas
23,Canada,Canada,Ottawa,41651653,English,Americas
24,Pakistan,Islamic Republic of Pakistan,Islamabad,241499431,English,Asia
25,India,Republic of India,New Delhi,1417492000,English,Asia
26,North Korea,조선민주주의인민공화국,Pyongyang,25950000,Korean,Asia
27,China,中华人民共和国,Beijing,1408280000,Chinese,Asia
28,Japan,日本,Tokyo,123210000,Japanese,Asia
29,Switzerland,Confédération suisse,Bern,9082848,French,Europe
30,Italy,Repubblica italiana,Rome,58927633,Italian,Europe
31,Norway,Kongeriket Noreg,Oslo,5606944,Norwegian Nynorsk,Europe

In [ ]:
df = df.reset_index(drop=True) # reset the index after dropping rows
df

,Name,Native Name,Capital(s),Population,Languages,Region
0,United States,United States of America,"Washington, D.C.",340110988,English,Americas
1,Canada,Canada,Ottawa,41651653,English,Americas
2,Pakistan,Islamic Republic of Pakistan,Islamabad,241499431,English,Asia
3,India,Republic of India,New Delhi,1417492000,English,Asia
4,North Korea,조선민주주의인민공화국,Pyongyang,25950000,Korean,Asia
5,China,中华人民共和国,Beijing,1408280000,Chinese,Asia
6,Japan,日本,Tokyo,123210000,Japanese,Asia
7,Switzerland,Confédération suisse,Bern,9082848,French,Europe
8,Italy,Repubblica italiana,Rome,58927633,Italian,Europe
9,Norway,Kongeriket Noreg,Oslo,5606944,Norwegian Nynorsk,Europe

### Last step: save data into clean CSV and JSON files

In [76]:
df.to_csv("countries_clean.csv", index=False) #save the dataframe as a csv file
print("DataFrame saved to countries_clean.csv")

df.to_json("countries_clean.json", orient="index", indent=4)
print("DataFrame saved to countries_clean.json")

DataFrame saved to countries_clean.csv
DataFrame saved to countries_clean.json